import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import {ShieldCheck,FileText,Target,Brain,LogOut,Upload,Download,Compass,Sparkles,Menu,Search} from "lucide-react";
import "./styles.css";

const API="https://cv-pilot-backend-slqp.onrender.com/api";
const empty={name:"",email:"",phone:"",location:"",summary:"",education:"",skills:"",experience:"",projects:"",certifications:"",linkedin:"",github:""};
const nav=[['builder','Resume Builder',FileText],['upload','Analyze Existing',Upload],['analyzer','ATS & Improve',Sparkles],['matcher','Job Matcher',Target],['career','Where To Apply',Compass],['interview','Interview Prep',Brain]];

function App(){const [token,setToken]=useState(localStorage.getItem("token")); if(!token)return <Auth onLogin={t=>{localStorage.setItem("token",t);setToken(t)}}/>; return <Dashboard token={token} logout={()=>{localStorage.removeItem("token");setToken(null)}}/>}
function Auth({onLogin}){const [mode,setMode]=useState('login'),[f,setF]=useState({name:'',email:'',password:''}),[err,setErr]=useState('');async function submit(e){e.preventDefault();let r=await fetch(`${API}/auth/${mode}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(f)});let d=await r.json();if(!r.ok)return setErr(d.error||'Request failed');onLogin(d.token)}return <div className="auth"><div className="brand"><ShieldCheck/> CV <span>PILOT</span></div><div className="authbox"><div className="eyebrow">AI RESUME INTELLIGENCE</div><h1>{mode==='login'?'Welcome back':'Create your account'}</h1><p>Build. Analyze. Improve. Apply smarter.</p><form onSubmit={submit}>{mode==='register'&&<input placeholder="Full name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/>}<input type="email" placeholder="Email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><input type="password" placeholder="Password (8+ characters)" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/>{err&&<div className="error">{err}</div>}<button className="primary">{mode==='login'?'Sign in':'Create account'}</button></form><button className="link" onClick={()=>{setMode(mode==='login'?'register':'login');setErr('')}}>{mode==='login'?'Create a new account':'Already registered? Sign in'}</button></div></div>}

function Dashboard({token,logout}){const [tab,setTab]=useState('builder'),[data,setData]=useState(empty),[analysis,setAnalysis]=useState(null),[job,setJob]=useState(''),[match,setMatch]=useState(null),[career,setCareer]=useState([]),[mobile,setMobile]=useState(false);const headers={'Content-Type':'application/json','Authorization':'Bearer '+token};const set=k=>e=>setData({...data,[k]:e.target.value});
 async function analyze(){let r=await fetch(API+'/analyze',{method:'POST',headers,body:JSON.stringify(data)});setAnalysis(await r.json());}
 async function save(){let r=await fetch(API+'/resumes',{method:'POST',headers,body:JSON.stringify({...data,title:data.name?`${data.name} Resume`:'My Resume'})});let d=await r.json();setAnalysis(d.analysis);alert('Resume saved successfully');}
 async function matchJob(){let r=await fetch(API+'/match',{method:'POST',headers,body:JSON.stringify({...data,job_description:job})});setMatch(await r.json())}
 async function careerFind(){let r=await fetch(API+'/career-recommendations',{method:'POST',headers,body:JSON.stringify(data)});setCareer((await r.json()).recommendations)}
 async function downloadPDF(){let r=await fetch(API+'/generate-pdf',{method:'POST',headers,body:JSON.stringify(data)});if(!r.ok)return alert('Could not generate PDF');let blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='CV_Pilot_Resume.pdf';a.click();URL.revokeObjectURL(url)}
 const current=nav.find(x=>x[0]===tab);return <div className="app"><aside className={mobile?'open':''}><div className="brand small"><ShieldCheck/> CV <span>PILOT</span></div><nav>{nav.map(([id,label,Icon])=><button key={id} onClick={()=>{setTab(id);setMobile(false)}} className={tab===id?'active':''}><Icon/>{label}</button>)}</nav><button className="logout" onClick={logout}><LogOut/> Logout</button></aside><main><header><button className="mobilemenu" onClick={()=>setMobile(!mobile)}><Menu/></button><div><p className="eyebrow">CV PILOT 2.0</p><h1>{current?.[1]}</h1></div></header>{tab==='builder'&&<Builder data={data} set={set} save={save} analyze={analyze} downloadPDF={downloadPDF}/>} {tab==='upload'&&<UploadResume token={token} setData={setData} setAnalysis={setAnalysis}/>} {tab==='analyzer'&&<Analyzer data={data} set={set} analysis={analysis} analyze={analyze}/>} {tab==='matcher'&&<Matcher data={data} set={set} job={job} setJob={setJob} match={match} matchJob={matchJob}/>} {tab==='career'&&<Career data={data} find={careerFind} career={career}/>} {tab==='interview'&&<Interview data={data}/>}</main></div>}

function Fields({data,set,compact=false}){let fields=[['summary','Professional Summary'],['education','Education'],['skills','Skills'],['experience','Experience'],['projects','Projects'],['certifications','Certifications & Achievements']];return <div className="grid">{!compact&&[['name','Full Name'],['email','Email'],['phone','Phone'],['location','Location'],['linkedin','LinkedIn'],['github','GitHub']].map(([k,l])=><label key={k}>{l}<input value={data[k]} onChange={set(k)} placeholder={l}/></label>)}{fields.map(([k,l])=><label key={k} className={['summary','education','experience','projects','certifications'].includes(k)?'wide':''}>{l}<textarea value={data[k]} onChange={set(k)} placeholder={`Enter ${l.toLowerCase()}...`}/></label>)}</div>}
function Builder({data,set,save,analyze,downloadPDF}){return <section><div className="card"><div className="cardhead"><div><h2>Build your resume</h2><p className="muted">Your information becomes the source of truth for every CV Pilot feature.</p></div><div className="badge">PRINT READY</div></div><Fields data={data} set={set}/><div className="actions"><button className="primary" onClick={save}>Save Resume</button><button onClick={analyze}>Analyze</button><button onClick={downloadPDF}><Download/> Download PDF</button></div></div></section>}
function UploadResume({token,setData,setAnalysis}){const [file,setFile]=useState(null),[busy,setBusy]=useState(false),[result,setResult]=useState(null);async function upload(){if(!file)return;setBusy(true);let fd=new FormData();fd.append('resume',file);let r=await fetch(API+'/upload-analyze',{method:'POST',headers:{Authorization:'Bearer '+token},body:fd});let d=await r.json();setBusy(false);if(!r.ok)return alert(d.error);setResult(d);setData(d.data);setAnalysis(d.analysis)}return <section><div className="card uploadcard"><Upload size={42}/><h2>Analyze an existing resume</h2><p className="muted">Upload a candidate's PDF or DOCX and CV Pilot will extract sections, detect skills and produce an ATS-focused improvement report.</p><label className="drop"><input type="file" accept=".pdf,.docx" onChange={e=>setFile(e.target.files[0])}/><strong>{file?file.name:'Choose PDF or DOCX'}</strong><span>Maximum 8 MB</span></label><button className="primary" disabled={!file||busy} onClick={upload}>{busy?'Analyzing...':'Upload & Analyze'}</button>{result&&<div className="results"><ScoreGrid analysis={result.analysis}/><h3>Extracted text preview</h3><pre className="preview">{result.analysis.extracted_text_preview}</pre></div>}</div></section>}
function ScoreGrid({analysis}){if(!analysis)return null;return <div className="scoregrid"><div className="metric"><b>{analysis.score}</b><span>Resume Score</span></div><div className="metric"><b>{analysis.ats_score}</b><span>ATS Score</span></div><div className="metric"><b>{analysis.word_count}</b><span>Words</span></div><div className="metric"><b>{analysis.skills.length}</b><span>Skills</span></div></div>}
function Analyzer({data,set,analysis,analyze}){return <section><div className="card"><h2>Precise improvement report</h2><p className="muted">CV Pilot separates strengths, priority fixes, and actionable improvements instead of giving you only one score.</p><Fields data={data} set={set} compact/><button className="primary" onClick={analyze}>Run Deep Analysis</button>{analysis&&<div className="results"><ScoreGrid analysis={analysis}/><div className="twocol"><div><h3>What is working</h3><ul className="good">{analysis.strengths?.map(x=><li>{x}</li>)}</ul></div><div><h3>Priority improvements</h3><ul>{analysis.suggestions?.map(x=><li>{x}</li>)}</ul></div></div><h3>Detected skills</h3><div className="chips">{analysis.skills.map(x=><span>{x}</span>)}</div></div>}</div></section>}
function Matcher({data,set,job,setJob,match,matchJob}){return <section><div className="card"><h2>Tailor your resume to a job</h2><Fields data={data} set={set} compact/><textarea className="job" value={job} onChange={e=>setJob(e.target.value)} placeholder="Paste the complete job description..."/><button className="primary" onClick={matchJob}>Analyze Match</button>{match&&<div className="results"><div className="heroScore">{match.match_score}% <small>overall match</small></div><div className="twocol"><div><h3>Matched</h3><div className="chips">{match.matched_skills.map(x=><span>{x}</span>)}</div></div><div><h3>Missing / improve</h3><div className="chips missing">{match.missing_skills.map(x=><span>{x}</span>)}</div></div></div><h3>Action plan</h3><ul>{match.actions.map(x=><li>{x}</li>)}</ul></div>}</div></section>}
function Career({data,find,career}){return <section><div className="card"><div className="cardhead"><div><h2>Where should I apply?</h2><p className="muted">Recommendations are based on the skills actually present in the profile. They are guidance, not guarantees of hiring.</p></div><Compass/></div><button className="primary" onClick={find}>Find career matches</button>{career.length>0&&<div className="careerlist">{career.map((x,i)=><div className="careeritem"><div className="role"><span className="rank">{i+1}</span><div><h3>{x.role}</h3><p>{x.matched.length} relevant skills found • {x.gaps.length} skill gaps</p></div></div><div className="matchpill">{x.match}% match</div><div className="chips">{x.matched.map(s=><span>{s}</span>)}</div><div className="gapline"><b>Areas to improve:</b> {x.gaps.join(', ')}</div><div className="searchlinks"><a target="_blank" rel="noreferrer" href={`https://www.linkedin.com/jobs/search/?keywords=${encodeURIComponent(x.role)}`}>Search LinkedIn Jobs</a><a target="_blank" rel="noreferrer" href={`https://www.indeed.com/jobs?q=${encodeURIComponent(x.role)}`}>Search Indeed</a></div></div>)}</div>}</div></section>}
function Interview({data}){const [qs,setQs]=useState([]);async function go(){let r=await fetch(API+'/interview',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+localStorage.getItem('token')},body:JSON.stringify({resume_text:Object.values(data).join(' '),role:'your target role'})});setQs((await r.json()).questions)}return <section><div className="card"><h2>Interview preparation</h2><p className="muted">Questions are generated from the projects and skills you put in your resume.</p><button className="primary" onClick={go}>Generate Questions</button><div className="questions">{qs.map((q,i)=><div><b>{i+1}</b>{q}</div>)}</div></div></section>}
createRoot(document.getElementById('root')).render(<App/>);
